# Generated by Django 5.0.4 on 2024-05-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
