# Generated by Django 5.0.3 on 2024-05-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_description',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
