# Generated by Django 5.0.6 on 2024-05-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_comment_thread_rename_postcategory_threadcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="thread",
            name="image_description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
