# Generated by Django 5.0.3 on 2024-05-05 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='header_image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
